image:
  repository: ghcr.io/xenitab/node-ttl
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext:
  #fsGroup: 65532
  seccompProfile:
    type: RuntimeDefault

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65532

service:
  probe:
    port: 8080
  metrics:
    port: 9090

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

serviceMonitor:
  enabled: false

networkPolicy:
  enabled: true

nodeTtl:
  interval: 10m
  statusConfigMapName: cluster-autoscaler-status
  statusConfigMapNamespace: cluster-autoscaler

customNodeLabelKey: "" # Must be set to a non-empty value to enable custom node label
# it should be a format string with one %s to be replaced by the custom node label value (e.g. "node-pool-%s")
# with optional regexp to match the node pool name against (e.g. "node-pool-(.*)")
customNodePoolNameFormat: "" # default: "%s"
