version: "2"
linters:
  enable:
    - cyclop
    - dogsled
    - dupl
    - errorlint
    - exhaustive
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gosec
    - lll
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nolintlint
    - prealloc
    - revive
    - thelper
    - unparam
    - whitespace
  settings:
    cyclop:
      max-complexity: 15
      package-average: 0
    dogsled:
      max-blank-identifiers: 2
    dupl:
      threshold: 100
    errcheck:
      check-type-assertions: true
      check-blank: true
    errorlint:
      errorf: true
      asserts: true
      comparison: true
    exhaustive:
      default-signifies-exhaustive: false
    funlen:
      lines: 80
      statements: 50
    gocognit:
      min-complexity: 20
    goconst:
      min-len: 3
      min-occurrences: 3
    gocritic:
      enabled-checks:
        - ruleguard
      enabled-tags:
        - performance
      disabled-tags:
        - experimental
      settings:
        captLocal:
          paramsOnly: true
        elseif:
          skipBalanced: true
        hugeParam:
          sizeThreshold: 80
        nestingReduce:
          bodyWidth: 5
        rangeExprCopy:
          sizeThreshold: 512
          skipTestFuncs: true
        rangeValCopy:
          sizeThreshold: 32
          skipTestFuncs: true
        ruleguard:
          rules: ""
        truncateCmp:
          skipArchDependent: true
        underef:
          skipRecvDeref: true
        unnamedResult:
          checkExported: true
    gocyclo:
      min-complexity: 20
    godot:
      scope: declarations
      capital: false
    lll:
      line-length: 140
      tab-width: 1
    makezero:
      always: false
    misspell:
      locale: US
    nakedret:
      max-func-lines: 30
    nestif:
      min-complexity: 5
    nolintlint:
      require-explanation: true
      require-specific: true
      allow-unused: false
    prealloc:
      simple: true
      range-loops: true
      for-loops: false
    revive:
      severity: warning
    staticcheck:
      checks:
        - all
    thelper:
      test:
        first: true
        name: true
        begin: true
      benchmark:
        first: true
        name: true
        begin: true
      tb:
        first: true
        name: true
        begin: true
    unparam:
      check-exported: true
    whitespace:
      multi-if: false
      multi-func: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - funlen
          - gocognit
          - gocyclo
          - unparam
        path: _test\.go
      - linters:
          - cyclop
        path: (.+)_test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  settings:
    gofmt:
      simplify: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
