name: cluster-autoscaler
on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/cluster-autoscaler.yaml"
jobs:
  image:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3
        with:
          repository: "kubernetes/autoscaler"
          ref: "cluster-autoscaler-1.26.0"
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Cluster Autoscaler with Kubemark
        run: |
          cd cluster-autoscaler
          BUILD_TAGS=kubemark make build
      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          push: true
          context: cluster-autoscaler
          file: ./cluster-autoscaler/Dockerfile.amd64
          platforms: linux/amd64
          tags: ghcr.io/xenitab/cluster-autoscaler-kubemark:1.26.0
          labels: |
            org.opencontainers.image.url=${{ github.event.repository.html_url }}
