name: tests
on:
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.x
          check-latest: true
          cache: true
      - name: Setup golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          args: --timeout 3m0s
  unit:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.x
          check-latest: true
          cache: true
      - name: Run tests
        run: make test
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.x
      - name: Setup Kubernetes
        uses: engineerd/setup-kind@v0.6.0
        with:
          version: v0.24.0
          skipClusterCreation: true
      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
           version: "v1.31.2"
      - name: Run e2e tests
        run: make e2e
